services:
  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    container_name: rabbitmq
    volumes:
      - ./container-data/prod/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - message

  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    volumes:
      - ./container-data/prod/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address :9001 /data
    networks:
      - storage

  gateway-db:
    image: mysql:8
    restart: unless-stopped
    container_name: gateway-db
    volumes:
      - ./container-data/prod/gateway-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gateway
      - MYSQL_ROOT_PASSWORD=${MYSQL_GATEWAY_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_GATEWAY_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_GATEWAY_PASSWORD}
    networks:
      - database

  gateway:
    image: balintjeszenszky/adsite:gateway-latest
    restart: unless-stopped
    container_name: gateway
    depends_on:
      - gateway-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=gateway-db:3306/gateway
      - DB_USER=${MYSQL_GATEWAY_USERNAME}
      - DB_PASS=${MYSQL_GATEWAY_PASSWORD}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - USER_SERVICE_URI=http://userservice:8080
      - ADVERTISEMENT_SERVICE_URI=http://advertisementservice:8080
      - IMAGE_SERVICE_URI=http://imageprocessingservice:8080
      - FRONTEND_URI=http://frontend:80
    networks:
      - web
      - database

  userservice-db:
    image: postgres:15
    restart: unless-stopped
    container_name: userservice-db
    volumes:
      - ./container-data/prod/userservice-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USERSERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERSERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=users
    networks:
      - database

  userservice:
    image: balintjeszenszky/adsite:userservice-latest
    restart: unless-stopped
    container_name: userservice
    depends_on:
      - userservice-db
      - rabbitmq
    environment:
      - DATABASE_URL=userservice-db:5432/users
      - DB_PASS=${USERSERVICE_POSTGRES_PASSWORD}
      - DB_USER=${USERSERVICE_POSTGRES_USER}
      - PORT=8080
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - web
      - database
      - message

  advertisementservice-db:
    image: mysql:8
    restart: unless-stopped
    container_name: advertisementservice-db
    volumes:
      - ./container-data/prod/advertisementservice-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=advertisements
      - MYSQL_ROOT_PASSWORD=${MYSQL_ADVERTISEMENTSERVICE_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_ADVERTISEMENTSERVICE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_ADVERTISEMENTSERVICE_PASSWORD}
    networks:
      - database

  advertisementservice:
    image: balintjeszenszky/adsite:advertisementservice-latest
    restart: unless-stopped
    container_name: advertisementservice
    depends_on:
      - advertisementservice-db
      - rabbitmq
      - minio
    environment:
      - DATABASE_URL=advertisementservice-db:3306/advertisements
      - DB_USER=${MYSQL_ADVERTISEMENTSERVICE_USERNAME}
      - DB_PASS=${MYSQL_ADVERTISEMENTSERVICE_PASSWORD}
      - MINIO_URL=http://minio:9000
      - MINIO_USER=${MINIO_ROOT_USER}
      - MINIO_PASS=${MINIO_ROOT_PASSWORD}
      - PORT=8080
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - web
      - database
      - message
      - storage

  imageprocessingservice-db:
    image: postgres:15
    restart: unless-stopped
    container_name: imageprocessingservice-db
    volumes:
      - ./container-data/prod/imageprocessingservice-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${IMAGEPROCESSING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IMAGEPROCESSING_POSTGRES_PASSWORD}
      - POSTGRES_DB=imageprocessing
    networks:
      - database

  imageprocessingservice:
    image: balintjeszenszky/adsite:imageprocessingservice-latest
    restart: unless-stopped
    container_name: imageprocessingservice
    depends_on:
      - imageprocessingservice-db
      - rabbitmq
      - minio
    environment:
      - DATABASE_URL=imageprocessingservice-db:5432/imageprocessing
      - DB_USER=${IMAGEPROCESSING_POSTGRES_USER}
      - DB_PASS=${IMAGEPROCESSING_POSTGRES_PASSWORD}
      - PORT=8080
      - MINIO_URL=http://minio:9000
      - MINIO_USER=${MINIO_ROOT_USER}
      - MINIO_PASS=${MINIO_ROOT_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - web
      - database
      - message
      - storage
  
  webscraperservice-db:
    image: mongo:5
    restart: unless-stopped
    container_name: webscraperservice-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=scraper
    volumes:
      - ./container-data/prod/webscraperservice-mongo:/data/db
    networks:
      - database

  webscraperservice:
    image: balintjeszenszky/adsite:webscraperservice-latest
    restart: unless-stopped
    container_name: webscraperservice
    depends_on:
      - webscraperservice-db
      - rabbitmq
    environment:
      - PORT=3000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - MONGO_URL=webscraperservice-db/scraper
      - MONGO_USER=${MONGO_USERNAME}
      - MONGO_PASS=${MONGO_PASSWORD}
    networks:
      - web
      - database
      - message

  frontend:
    image: balintjeszenszky/adsite:frontend-latest
    restart: unless-stopped
    container_name: frontend
    networks:
      - web

networks:
  web:
    name: web
  database:
    name: database
  message:
    name: message
  storage:
    name: storage
