apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice-deployment
  labels:
    app: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
      - name: chatservice
        image: balintjeszenszky/adsite:chatservice-latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: '3000'
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: chatservice-db-config
              key: chatservice-db-url
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: chatservice-db-config
              key: chatservice-db-name
        - name: DB_PORT
          value: '3306'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: chatservice-db-secret
              key: chatservice-db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: chatservice-db-secret
              key: chatservice-db-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: chatservice-redis-config
              key: chatservice-redis-url
        - name: REDIS_PORT
          value: '6379'
        - name: ADVERTISEMENT_SERVICE_INTERNAL_API_URL
          valueFrom:
            configMapKeyRef:
              name: advertisementservice-config
              key: advertisementservice-internal-api-url
        - name: ADVERTISEMENT_SERVICE_ADVERTISEMENT_EXISTS_PATH
          valueFrom:
            configMapKeyRef:
              name: advertisementservice-config
              key: advertisementservice-advertisement-exists-path
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice-service
spec:
  type: NodePort
  selector:
    app: chatservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30302
