openapi: 3.0.0
x-stoplight:
  id: 5r8fq3dp1cw8j
info:
  title: openapi
  version: '1.0'
  contact:
    name: Balint Jeszenszky
  description: lassified advertisement site gateway
servers:
  - url: 'http://localhost:8080'
tags:
  - name: auth
paths:
  /api/auth/login:
    post:
      summary: ''
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
      description: Log in user
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
  /api/auth/refresh:
    post:
      summary: ''
      operationId: post-api-auth-refresh
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshResponse'
        '401':
          description: Unauthorized
      tags:
        - auth
      description: Refresh login with a refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        description: ''
  /api/auth/logout:
    delete:
      summary: ''
      operationId: delete-api-auth-logout
      responses:
        '204':
          description: No Content
      tags:
        - auth
      description: Destroy refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
components:
  schemas:
    LoginRequest:
      title: LoginRequest
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      description: ''
    UserDetailsResponse:
      title: UserDetailsResponse
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - roles
    LoginResponse:
      title: LoginResponse
      x-stoplight:
        id: rkbfkb7quha0d
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserDetailsResponse'
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - user
        - accessToken
        - refreshToken
    LogoutRequest:
      title: LogoutRequest
      x-stoplight:
        id: f293nn5oep713
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    RefreshRequest:
      title: RefreshRequest
      x-stoplight:
        id: f958cfd92e2eb
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    RefreshResponse:
      title: RefreshResponse
      x-stoplight:
        id: dk41kyqm3rf20
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken
