openapi: 3.0.0
x-stoplight:
  id: l0nx7tow1fxgm
info:
  title: internal
  version: '1.0'
  contact:
    name: Balint Jeszenszky
  description: Classified advertisement site advertisement service internal api
servers:
  - url: 'http://localhost:8082/api/advertisement/internal'
paths:
  '/advertisement/exists/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: ''
      operationId: get-advertisement-exists-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertisementExistsResponse'
        '404':
          description: Not Found
      description: 'check if an advertisement exists, returns advertiser user id'
      tags:
        - advertisement
components:
  schemas:
    AdvertisementExistsResponse:
      title: AdvertisementExistsResponse
      x-stoplight:
        id: c2111dd4a3778
      type: object
      properties:
        advertiserId:
          type: number
      required:
        - advertiserId
x-internal: true
tags:
  - name: advertisement
