apiVersion: v1
kind: Secret
metadata:
  name: imageprocessingservice-db-secret
type: Opaque
data:
  imageprocessingservice-db-user: aW1hZ2Vwcm9jZXNzaW5nc2VydmljZS1kYi11c2Vy # TODO use env variables
  imageprocessingservice-db-password: aW1hZ2Vwcm9jZXNzaW5nc2VydmljZS1kYi1wYXNzd29yZA==
