apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidservice-deployment
  labels:
    app: bidservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidservice
  template:
    metadata:
      labels:
        app: bidservice
    spec:
      containers:
      - name: bidservice
        image: balintjeszenszky/adsite:bidservice-latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: bidservice-db-config
              key: bidservice-db-url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bidservice-db-secret
              key: bidservice-db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bidservice-db-secret
              key: bidservice-db-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-url
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        - name: USER_API_URL
          valueFrom:
            configMapKeyRef:
              name: userservice-config
              key: userservice-api-url
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bidservice-redis-config
              key: bidservice-redis-url
        - name: REDIS_PORT
          value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: bidservice-service
spec:
  type: NodePort
  selector:
    app: bidservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30084
