apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bidservice-redis-deployment
  labels:
    app: bidservice-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidservice-redis
  template:
    metadata:
      labels:
        app: bidservice-redis
    spec:
      containers:
      - name: bidservice-redis
        image: redis:7
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: bidservice-redis-service
spec:
  selector:
    app: bidservice-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
