apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  jwt-expiration: NjAwMDAw # TODO use env variables
  jwt-refresh-expiration: NjA0ODAwMDAw
  jwt-secret: and0LXNlY3JldA==
  jwt-refresh-secret: and0LXJlZnJlc2gtc2VjcmV0
