apiVersion: v1
kind: Secret
metadata:
  name: gateway-db-secret
type: Opaque
data:
  gateway-db-root-password: Z2F0ZXdheS1kYi1yb290LXBhc3N3b3Jk # TODO use env variables
  gateway-db-user: Z2F0ZXdheS1kYi11c2Vy
  gateway-db-password: Z2F0ZXdheS1kYi1wYXNzd29yZA==
