apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertisementservice-deployment
  labels:
    app: advertisementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertisementservice
  template:
    metadata:
      labels:
        app: advertisementservice
    spec:
      containers:
      - name: advertisementservice
        image: balintjeszenszky/adsite:advertisementservice-latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: advertisementservice-db-config
              key: advertisementservice-db-url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: advertisementservice-db-secret
              key: advertisementservice-db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: advertisementservice-db-secret
              key: advertisementservice-db-password
        - name: MINIO_URL
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: minio-url
        - name: MINIO_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio-user
        - name: MINIO_PASS
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-url
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: advertisementservice-service
spec:
  type: NodePort
  selector:
    app: advertisementservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
