openapi: 3.0.0
info:
  title: openapi
  version: '1.0'
  contact:
    name: Balint Jeszenszky
  description: Classified advertisement site user service
servers:
  - url: 'http://localhost:8081/api/user'
tags:
  - name: authentication
paths:
  /auth/login:
    post:
      summary: ''
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
      description: Log in user
      tags:
        - authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
    parameters: []
  /auth/register:
    parameters: []
    post:
      summary: ''
      operationId: post-auth-reguster
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      tags:
        - authentication
      description: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
components:
  schemas:
    UserDetailsResponse:
      title: UserDetailsResponse
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - roles
    LoginRequest:
      title: LoginRequest
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      description: ''
    RegistrationRequest:
      title: RegistrationRequest
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      required:
        - username
        - email
        - password
        - confirmPassword
