name: CICD

on:
  push:
    branches: [ main, release, dev ]
  pull_request:
    branches: [ main, release, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17

    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build Gateway
      run: cd gateway && mvn install -DskipTests

    - name: Build User service
      run: cd userservice && mvn install -DskipTests

    - name: Build Advertisement service
      run: cd advertisementservice && gradle build -x test

    - name: Build Image processing service
      run: cd imageprocessingservice && mvn install -DskipTests

    - name: Build Web scraping service
      run: cd web-scraping-service && npm install && npm run build

    - name: Build Notifivation service
      run: cd notificationservice && npm install && npm run build

    - name: Build Chat service
      run: cd chat-service && npm install && npm run build

    - name: Build Bid service
      run: cd bidservice && gradle build -x test

    - name: Build Frontend
      run: cd classified-advertisement-site-frontend && npm install && npm run openapi:generate && npm run graphql:generate && npm run build

  unit_test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17

    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Test User service
      run: cd userservice && mvn test

    - name: Test Advertisement service
      run: cd advertisementservice && gradle test --tests "*Test"

    - name: Test Image processing service
      run: cd imageprocessingservice && mvn test

    - name: Test Web scraping service
      run: cd web-scraping-service && npm install && npm test

    - name: Test Notifivation service
      run: cd notificationservice && npm install && npm test

    - name: Test Chat service
      run: cd chat-service && npm install && npm test

    - name: Test Bid service
      run: cd bidservice && gradle test --tests "*Test"
